[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'osyo-manga/vim-marching'


